<?php
namespace app\model;
use core\Model;

class Booking extends Model{
    
    protected static string $tableName = "booking";
    protected static string $className = "Booking";
    protected static $primaryKey = array("bookingID");
    protected static bool $isAutoGenerated = true;

    public int $bookingID = 0;
    public string $bookName = "";
    public string $bookEmail = "";
    public string $bookTime = "";
    public string $methodPay = "";
    public bool $isPaid = false;
    public ?int $userID = 0;
    public bool $isDeleted = false;
}