<?php

namespace app\model;
use core\Model;

class Cinema extends Model{
    protected static string $tableName = "cinema";
    protected static string $className = "Cinema";
    protected static string $primaryKey = "cinemaID";
    protected static bool $isAutoGenerated = true;

    protected int $cinemaID;
    protected string $cinemaName;
    protected string $cinemaAddress;
    protected string $mapLink;
    protected ?int $provinceID;
}