<?php
namespace app\model;
use core\Model;

class FeaturePermission extends Model{
    protected static string $tableName = "feature_permission";
    protected static string $className = "FeaturePermission";
    protected static $primaryKey = array("permissionID", "featureID", "actionName");
    protected static bool $isAutoGenerated = false;

    public int $permissionID;
    public int $featureID;
    public int $actionName;
    public bool $isActive;
    public string $webPath;
    public bool $isDeleted;
}