<?php
namespace app\model;
use core\Model;

class Feature extends Model{
    protected static string $tableName = "feature";
    protected static string $className = "Feature";
    protected static $primaryKey = array("featureID");
    protected static bool $isAutoGenerated = true;

    public int $featureID;
    public string $featureName;
    
}