<?php
namespace app\model;
use core\Model;

class FeaturePermission extends Model{
    protected static string $tableName = "feature_permission";
    protected static string $className = "FeaturePermission";
    protected static $primaryKey = array("permissionID", "featureID", "actionName");
    protected static bool $isAutoGenerated = false;

    public int $permissionID = 0;
    public int $featureID = 0;
    public bool $isActive = false;
}