<?php
namespace app\model;
use core\Model;

class Food extends Model{
    protected static string $tableName = "food";
    protected static string $className = "Food";
    protected static $primaryKey = array("foodID");
    protected static bool $isAutoGenerated = true;

    public int $foodID = 0;
    public string $foodImage = "";
    public string $foodName = "";
    public int $foodPrice = 0;
    public string $foodDescription = "";
    public ?int $discountID = null;
    public bool $isDeleted = false;
}