<?php
namespace app\model;
use core\Model;

class GroupPermission extends Model{
    protected static string $tableName = "group_permission";
    protected static string $className = "GroupPermission";
    protected static $primaryKey = array("permissionID");
    protected static bool $isAutoGenerated = true;

    public int $permissionID;
    public string $groupName;
    
}