<?php
namespace app\model;
use core\Model;

class MovieCategory extends Model{
    protected static string $tableName = "movie_category";
    protected static string $className = "MovieCategory";
    protected static $primaryKey = array("categoryID", "movieID");
    protected static bool $isAutoGenerated = false;

    public int $movieID;
    public int $categoryID;
}