<?php

namespace app\model;
use core\Model;

class Movie extends Model
{
    // Model database data
    protected static string $tableName = "movie";
    protected static string $className = "Movie";
    protected static $primaryKey = array("movieID");
    protected static bool $isAutoGenerated = true;

    // Model property
    public int $movieID;
    public string $movieName;
    public string $movieDes;
    public string $posterLink;
    public string $landscapeLink;
    public string $trailerLink;
    public string $movieDirectors;
    public string $movieActors;
    public int $duringTime;
    public string $dateRelease;
    public string $movieLanguage;
    public bool $isFeatured;
    public ?int $tagID;
    public bool $isDeleted;
}