<?php

namespace app\model;
use core\Model;

class MovieDetail extends Model
{
    protected static string $tableName = "MOVIE";
    protected static string $className = "Movie";
    protected static string $primaryKey = "movieID";
    protected static bool $isAutoGenerated = false;
    public $movieID;
    public $title;
    public $descriptions;
    public $poster_link;
    public $trailer_link	;
    public  $director ;
    public $actor;
    
    public $start_show;
    
    public $tagID;
    
    public $categoryID	;

    public $during_time ;

    public $movie_language;
}
?>