<?php

namespace app\model;
use core\Model;

class Movie extends Model
{
    // Model database data
    protected static string $tableName = "MOVIE";
    protected static string $className = "Movie";
    protected static string $primaryKey = "movieID";
    protected static bool $isAutoGenerated = false;

    // Model property
    public string $movieID = "movie100";
    public string $movie_name = "Hello Duy";
    public string $movie_description = "ad ahdhahd";
    public string $movie_img = "abd";
    public string $movie_trailer ="dadbab";
    public string $timestamp;
}