<?php

namespace app\model;
use core\Model;

class Movie extends Model
{
    // Model database data
    protected static string $tableName = "movie";
    protected static string $className = "Movie";
    protected static $primaryKey = array("movieID");
    protected static bool $isAutoGenerated = true;

    // Model property
    public int $movieID = 0;
    public string $movieName = "";
    public string $movieDes = "";
    public string $posterLink = "";
    public string $landscapePoster = "";
    public string $trailerLink = "";
    public string $movieDirectors = "";
    public string $movieActors = "";
    public int $duringTime = 0;
    public string $dateRelease = "";
    public string $movieLanguage = "";
    public bool $isFeatured = false;
    public ?int $tagID = null;
    public bool $isDeleted = false;
    public int $externalID = 0;
}