<?php

namespace app\model;
use core\Model;

class Province extends Model{
    protected static string $tableName = "province";
    protected static string $className = "Province";
    protected static string $primaryKey = "provinceID";
    protected static bool $isAutoGenerated = true;

    protected int $provinceID;
    protected string $provinceName;
}