<?php

namespace app\model;
use core\Model;

class Province extends Model{
    protected static string $tableName = "province";
    protected static string $className = "Province";
    protected static $primaryKey = array("provinceID");
    protected static bool $isAutoGenerated = true;

    public int $provinceID;
    public string $provinceName;
}