<?php
namespace app\model;
use core\Model;
//2 primary key
class Rating extends Model{
    protected static string $tableName = "rating";
    protected static string $className = "Rating";
    protected static $primaryKey = array("movieID", "userID");
    protected static bool $isAutoGenerated = false;

    public int $movieID;
    public int $userID;
    public int $ratingScore;
    public string $pickedAt;
    
}