<?php
namespace app\model;
use core\Model;

class Room extends Model{
    protected static string $tableName = "room";
    protected static string $className = "Room";
    protected static $primaryKey = array("roomID");
    protected static bool $isAutoGenerated = true;

    public int $roomID;
    public string $roomName;
    public int $numberOfRow;
    public int $numberOfCol;
    public ?int $cinemaID;
}