<?php
namespace app\model;
use core\Model;

//2 primary key
class SeatShowtime extends Model{
    protected static string $tableName = "seat_showtime";
    protected static string $className = "SeatShowTime";
    protected static $primaryKey = array("showID", "seatID");
    protected static bool $isAutoGenerated = false;

    public int $showID;
    public int $seatID;
    public string $pickedAt;
    public long $seatPrice;
    public bool $isBooked;
    public ?int $userID;
    public ?int $bookingID;
}