<?php
namespace app\model;
use core\Model;

class Seat extends Model{
    protected static string $tableName = "seat";
    protected static string $className = "Seat";
    protected static $primaryKey = array("seatID");
    protected static bool $isAutoGenerated = true;

    public int $seatID;
    public char $seatRow;
    public int $seatCol;
    public ?int $eatType;
    public ?int $roomID;
}