<?php
namespace app\model;
use core\Model;

//2 primary key
class SeatShowtime extends Model{
    protected static string $tableName = "seat_showtime";
    protected static string $className = "SeatShowTime";
    protected static $primaryKey = array("showID", "seatID");
    protected static bool $isAutoGenerated = false;

    public int $showID = 0;
    public int $seatID = 0;
    public string $pickedAt = "";
    public int $seatPrice = 0;
    public bool $isBooked = true;
    public ?int $userID = null;
    public ?int $bookingID = null;
}