<?php
namespace app\model;
use core\Model;

class Seat extends Model{
    protected static string $tableName = "seat";
    protected static string $className = "Seat";
    protected static $primaryKey = array("seatID");
    protected static bool $isAutoGenerated = true;

    public int $seatID = 0;
    public string $seatRow = "";
    public int $seatCol = 0;
    public ?int $seatType = 0;
    public ?int $roomID = 0;
}