<?php
namespace app\model;
use core\Model;

class SeatType extends Model{
    protected static string $tableName = "seat_type";
    protected static string $className = "SeatType";
    protected static $primaryKey = array("seatType");
    protected static bool $isAutoGenerated = true;

    public int $seatType;
    public string $typeName;
}