<?php

namespace app\model;
use core\Model;

class Showtime extends Model{
    protected static string $tableName = "showtime";
    protected static string $className = "Showtime";
    protected static $primaryKey = array("showID");
    protected static bool $isAutoGenerated = true;

    public int $showID = 0;
    public string $timeStart = "";
    public int $duringTime = 0;
    public ?int $roomID = 0;
    public ?int $movieID = 0;
    public bool $isDeleted = false;
}