<?php

namespace app\model;
use core\Model;

class Showtime extends Model{
    protected static string $tableName = "showtime";
    protected static string $className = "Showtime";
    protected static $primaryKey = array("showID");
    protected static bool $isAutoGenerated = true;

    public int $showID=0;
    public string $timeStart;
    public int $duringTime;
    public ?int $roomID;
    public ?int $movieID;
    public bool $isDeleted;
}