<?php
namespace app\model;
use core\Model;
//hai primary key nên chưa biết hướng giải quyết
class ShowtimePrice extends Model{
    protected static string $tableName = "showtime_price";
    protected static string $className = "ShowtimePrice";
    protected static $primaryKey = array("showID", "seatType");
    protected static bool $isAutoGenerated = false;

    public int $showID = 0;
    public int $seatType = 0;
    public int $ticketPrice = 0;
    public ?int $discountID = null;
    public bool $isDeleted = false;
}