<?php

namespace app\model;
use core\Model;

class User extends Model
{
    protected static string $tableName = "account";
    protected static string $className = "User";
    protected static string $primaryKey = "accountID";
    protected static bool $isAutoGenerated = true;

    //View property
    public int $accountID;
    public string $username;
    public string $password;
    public string $email;
    public string $phone;
    public bool $is_active;
    public bool $is_admin;
    public bool $is_verity;
    public string $created_at;
    public int $permissionID;

    
}

