<?php

namespace app\model;
use core\Model;

class User extends Model
{
    protected static string $tableName = "user";
    protected static string $className = "User";
    protected static string $primaryKey = "userID";
    protected static bool $isAutoGenerated = true;

    //View property
    public int $userID = 0;
    public string $email;
    public string $fullName;
    public string $userPassword;
    public bool $isActive;
    public string $createAt;
    public ?int $permissionID = 1;

    
}

